# Generated by Django 3.2.16 on 2022-10-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='numbers',
        ),
    ]
