# Generated by Django 3.2.16 on 2023-07-31 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='job.worker'),
        ),
    ]
