# Generated by Django 3.2.16 on 2022-10-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_home_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to='photo_de_profile', verbose_name='Photo de profile'),
        ),
    ]
