# Generated by Django 3.2.16 on 2023-07-31 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('nom_du_metier', models.CharField(max_length=50, verbose_name='Ton Métier')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('photo', models.ImageField(upload_to='photos')),
                ('bio', models.CharField(max_length=200)),
                ('adress_home', models.CharField(max_length=50)),
                ('contact', models.IntegerField(max_length=12, null=True)),
                ('zone_de_deplacement', multiselectfield.db.fields.MultiSelectField(choices=[('DAKAR', 'DAKAR'), ('THEIS', 'THEIS'), ('LOUGA', 'LOUGA')], max_length=30)),
                ('jours_de_travaille', multiselectfield.db.fields.MultiSelectField(choices=[('LUNDI', 'LUNDI'), ('MARDI', 'MARDI'), ('MERCREDI', 'MERCREDI'), ('JEUDI', 'JEUDI'), ('VENDREDI', 'VENDREDI'), ('DIMANCHE', 'DIMANCHE'), ('DIMANCHE', 'DIMANCHE')], max_length=53)),
                ('heures_de_travaille', models.CharField(choices=[('JOURNEE', 'JOURNEE'), ('NUIT', 'NUIT')], max_length=30)),
                ('etoile', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('metier', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='job.metier')),
                ('ouvrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouvrier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
