# Generated by Django 4.1 on 2022-10-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_metier_metier_nom_du_metier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metier',
            name='description',
        ),
        migrations.RemoveField(
            model_name='metier',
            name='heure_de_travaille',
        ),
        migrations.RemoveField(
            model_name='metier',
            name='jour_de_travaille',
        ),
        migrations.RemoveField(
            model_name='metier',
            name='zone_de_deplacement',
        ),
        migrations.AddField(
            model_name='metier',
            name='slug',
            field=models.SlugField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='heure_de_travaille',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='jour_de_travaille',
            field=models.CharField(choices=[('LUNDI', 'LUNDI'), ('MARDI', 'MARDI'), ('MERCREDI', 'MERCREDI'), ('JEUDI', 'JEUDI'), ('VENDREDI', 'VENDREDI'), ('DIMANCHE', 'DIMANCHE'), ('DIMANCHE', 'DIMANCHE')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='zone_de_deplacement',
            field=models.CharField(choices=[('DAKAR', 'DAKAR'), ('THEIS', 'THEIS'), ('LOUGA', 'LOUGA')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
