# Generated by Django 3.2.16 on 2022-10-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_metier_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
