# Generated by Django 3.2.16 on 2022-10-28 12:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_worker_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='zone_de_deplacement',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DAKAR', 'DAKAR'), ('THEIS', 'THEIS'), ('LOUGA', 'LOUGA')], max_length=30),
        ),
    ]
