# Generated by Django 3.2.16 on 2022-10-30 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_worker_zone_de_deplacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='heure_de_travaille',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='jour_de_travaille',
        ),
        migrations.AddField(
            model_name='worker',
            name='heures_de_travaille',
            field=models.CharField(choices=[('JOURNEE', 'JOURNEE'), ('NUIT', 'NUIT')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='jours_de_travaille',
            field=models.CharField(choices=[('LUNDI', 'LUNDI'), ('MARDI', 'MARDI'), ('MERCREDI', 'MERCREDI'), ('JEUDI', 'JEUDI'), ('VENDREDI', 'VENDREDI'), ('DIMANCHE', 'DIMANCHE'), ('DIMANCHE', 'DIMANCHE')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='contact',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
