# Generated by Django 3.2.16 on 2022-10-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20221030_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='contact',
            field=models.IntegerField(max_length=12),
        ),
    ]
