# Generated by Django 3.2.16 on 2022-12-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_worker_jours_de_travaille'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='slug',
            field=models.SlugField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
